### ISSUE TITLE
"Contextual $*FileSystem not found" when running test suite

### ISSUE THREAD

**Issue by leto** [Whiteknight/parrot-linear-algebra#19]
Full output is here:

http://gist.github.com/572779

This was using kakapo cb9b6b0a16bb145c32b0b2ba71b3f011b4a9d6a6 and parrot r48772.

**Comment by Whiteknight** [comment]
This is resolved by using the special forked version of Kakapo, as discussed in the README and in other documentation. We will continue to use a forked version until Kakapo master becomes more stable, or until a more compelling unit-testing solution can be found
