### ISSUE TITLE
Documentation: Update "fill" parameters order and expand item_at

### ISSUE THREAD

**Issue by fernandobrito** [Whiteknight/parrot-linear-algebra#21]
http://whiteknight.github.com/parrot-linear-algebra/pmcs/methods/nummatrix2d.html

Fill params are: 
 fill(value, rows, cols) 
and not 
 fill(rows, cols, value)

It should be also in the documentation that item_at accepts 3 parameters (to set an item).

**Comment by Whiteknight** [comment]
Fixed, thanks.
